version: "1.0"
info:
  model: int-scaffold
packages:
- name: DemoGit1Project
  gitServerName: Dima
  gitUrl: https://github.com/deemashlayer/DemoGit1Project
  gitUsername: deemashlayer
  gitBranch: main
- name: DepDemoPackage
  gitServerName: Dima
  gitUrl: https://github.com/deemashlayer
  gitUsername: deemashlayer
  gitBranch: master
services:
- serviceName: project.demogit1.integrations:currDateGit1
  packages:
  - name: DemoGit1Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.686
- serviceName: project.demogit1.integrations:depCurrDateService
  packages:
  - name: DemoGit1Project
    version: "1.0"
  - name: DepDemoPackage
    version: "1.0"
- serviceName: demo:simpleService
  packages:
  - name: DepDemoPackage
    version: "1.0"
