version: "1.0"
info:
  model: int-scaffold
packages:
- name: DemoGit1Project
  gitServerName: Dima
  gitUrl: https://github.com/deemashlayer/DemoGit1Project
  gitUsername: deemashlayer
  gitBranch: main
- name: DepDemoPackage
  gitServerName: Dima
  gitUrl: https://github.com/deemashlayer
  gitUsername: deemashlayer
  gitBranch: master
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
services:
- serviceName: project.demogit1.integrations:currDateGit1
  packages:
  - name: DemoGit1Project
    version: "1.0"
  - name: DepDemoPackage
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.686
- serviceName: project.demogit1.integrations:depCurrDateService
  packages:
  - name: DemoGit1Project
    version: "1.0"
  - name: DepDemoPackage
    version: "1.0"
- serviceName: demo:simpleService
  packages:
  - name: DepDemoPackage
    version: "1.0"
- serviceName: project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_Demo
  packages:
  - name: DemoGit1Project
    version: "1.0"
  - name: DepDemoPackage
    version: "1.0"
configurationVariables:
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.user
  : JDBC_BVT
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.trustStore
  : ""
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.keyStore
  : ""
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.databaseName
  : ORCL
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.portNumber
  : "1521"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionEnabled
  : "false"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.otherProperties
  : loginTimeout=60;otherProperties=driverType=thin;
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.dbType
  : ORACLE
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.password
  : "{AES}gOk3wygfWVjWqDc4SLehnQ=="
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.poolable
  : "false"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.networkProtocol
  : tcp
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.DemoGit1Project.project.demogit1.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_Demo.connectionSettings.transactionType
  : NO_TRANSACTION
